### ISSUE TITLE
Support bounds on operators.

### ISSUE THREAD

**Issue by alex-ozdemir** [alex-ozdemir/algebra-dsl#1]
Some mathematical operators can have associated bounds. To name a few $\sum, \prod, \int, \lim$. 

Similarly, for other operators "upper bounds" should be interpreted as powers ($\sin, \log$).

We should know how to parse these things.

**Comment by cmiddlemas** [comment]
It might be nice to add a domain object to our representation. That could help handle sum, prod, and int, as well as play a behind the scenes role in functions such as sqrt and log. Not sure about \lim though.

Matrices on the other hand seem pretty trivial to parse and emit. The only question is how we represent them internally. It’d just be another option under Expression, but we might want something a bit more sophisticated then Matrix(Vec<Vec<Expression>>).
