### ISSUE TITLE
Negation of Products

### ISSUE THREAD

**Issue by cmiddlemas** [alex-ozdemir/algebra-dsl#16]
Currently, the negation of products does weird things.

Example:

$-xy parses as (-x)*y

but

$x^2 - xy parses as x^2 + (-xy).

**Comment by cmiddlemas** [comment]
Basically, should we have a consistent guarantee for order of these things?

**Comment by alex-ozdemir** [comment]
I'll take care of it tonight.

This just requires a precedence change.
