### ISSUE TITLE
Allow for LaTeX we don't understand

### ISSUE THREAD

**Issue by alex-ozdemir** [alex-ozdemir/algebra-dsl#17]
While we're going to try to support as large a subset of LaTeX math as possible, we won't get everything.

To that end I think we should have a way for the user to say "treat this LaTeX as a variable".  It would function atomically in transformations, would be rendered to MathML as transparently as possible (e.g. like \verb||), and would be outputted to LaTeX in its orginal form. Possible syntax below:

```
$ 5 = 6 \cdot #\`a#
$ 5 = 6 \cdot #{\`a}#
$ 5 = 6 \cdot {{{\`a}}}
$ 5 = 6 \cdot %\`a%
$ 5 = 6 \cdot @`a@
```

Advantages of `%`: it will never be part of LaTeX math (so long as we check for escaping).

**Comment by AdamCDunlap** [comment]
Do you mean it to look like this? 
![mathinmath](https://cloud.githubusercontent.com/assets/1733611/23088996/618e8bc4-f537-11e6-9016-366e6e1065ed.png)
