### ISSUE TITLE
Old equation not printed when an error occurs

### ISSUE THREAD

**Issue by AdamCDunlap** [alex-ozdemir/algebra-dsl#20]
Regression from 7ed9be6f1b2b3704e3f0fdfa09db1855728b81b2

**Comment by alex-ozdemir** [comment]
Investigating

**Comment by alex-ozdemir** [comment]
Issue caused here: e520a89cc9e32f374656b8c4646452a6c7bf306f. Turns out that it is a `div`, not a `span`, and furthermore, in html tagnames are [uppercase](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName).
