### ISSUE TITLE
Show parentheses in otherwise associative structures

### ISSUE THREAD

**Issue by alex-ozdemir** [alex-ozdemir/algebra-dsl#29]
Our internal representation current distinguishes between the trees `a + (b + c)` and `a + b + c`, but the two are displayed the same. Various operations might produce the former, even though it cannot be directly entered.

This can cause make/delete to behave surprisingly because `a` and `b` are not siblings in the tree `a + (b + c)` even those the tree displays as *a + b + c*.

As an immediate goal we should display the parentheses in this situation.

Relevant cases:
* Sum within Sum
* Division (Product form, that is, no denominator) within Division

In the long run we might want the user to be able to directly produce a tree like `a + (b + c)`.

**Comment by cmiddlemas** [comment]
Do you have an example of how to produce a tree like that in the front end? I have code written to fix this, and it passes a basic test, but I want to try it out on harder examples.

**Comment by alex-ozdemir** [comment]
I only have code for Division:

```
$ ab
make `a` ac
```

and similar (and substitution of a product (no-denominator Division) within a Division
