### ISSUE TITLE
Parens not displayed when a number is being multiplied by another number to a power

### ISSUE THREAD

**Issue by AdamCDunlap** [alex-ozdemir/algebra-dsl#31]
For example, the input `$2*3^{1/2}` displays as `23^{1/2}`

**Comment by AdamCDunlap** [comment]
It appears the LaTeX outputs it correctly, although I had a previous example that I don't think it worked on, but I'm not sure.

![untitled](https://cloud.githubusercontent.com/assets/1733611/23200945/1460df34-f88c-11e6-9310-86d94b75f265.png)

**Comment by cmiddlemas** [comment]
Fixing this by using explicit times, since that's the current strategy for outputting things like 2 * 3.
