### ISSUE TITLE
Fix Replace: Indices Invalidated

### ISSUE THREAD

**Issue by cmiddlemas** [alex-ozdemir/algebra-dsl#38]
Currently, we have some problems with indices being invalidated during a replace call. This happens because the underlying replace command implements some flattening, which we want to either delay or handle dynamically.

**Comment by AdamCDunlap** [comment]
Status on this? I don't have a good enough understanding of the problem to fix it and I haven't seen it come up.

**Comment by cmiddlemas** [comment]
Example sequence that does this. Try
```
$ x + y + z
replace (click y) (click z) a + a
```
This currently yields x + a + a + a +z, instead of the expected x + a + a + a + a.
If it's still open tomorrow though, I'll fix it.

**Comment by alex-ozdemir** [comment]
I'll take it.

My vision is to have a `flatten` method that potentially merges the children of the specified `Expr`.

To handle this issue, there will be a `flatten_many` method, that flattens many indices, and is careful to do them all correctly.

**Comment by alex-ozdemir** [comment]
Closed by a57622a930847180fe1955821976d006c3a8161f
