### ISSUE TITLE
Handle Errors Better

### ISSUE THREAD

**Issue by AdamCDunlap** [alex-ozdemir/algebra-dsl#49]
There are some things that are easy, such as writing a real `Display::fmt` method for `AlgebraDSLError`. But we should think about adding an (optional?) string to some of the types of errors so a more specific thing can be printed in some cases.

**Comment by alex-ozdemir** [comment]
Strongly agree!

**Comment by AdamCDunlap** [comment]
Specifically, we can write `Display::fmt` whenever we want, but I think it's important to add the string or other mechanism soon because going back over our code to try to figure out why an error is thrown in each case could be annoying, but while writing code it's generally easy to write these error messages.
