### ISSUE TITLE
Parser panics if given close close-paren or bracket with other text

### ISSUE THREAD

**Issue by AdamCDunlap** [alex-ozdemir/algebra-dsl#5]
The lines `a )` and `a ]` panic `'No arity for these', ..../khwarizmi/src/parser/mod.rs:89`

Perhaps the `arity` function could return an Option?

**Comment by alex-ozdemir** [comment]
Yep! On it.

**Comment by alex-ozdemir** [comment]
Same issue for `( a` (also fixed).
